[workspace]
members = [ "color-palette", "starfield"]

[package]
name = "railroad-handcar"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace.dependencies]
macroquad = "0.4.5"
rand = "0.8.5"
color-palette = { path = "./color-palette"}
