[package]
name = "Starfield"
version = "0.1.0"
authors = ["Queso"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
p5-sys = { workspace = true }
wasm-bindgen = { workspace = true }
